### ISSUE TITLE
does it work for ubuntu as well

### ISSUE THREAD

**Issue by onksingh** [remyma/ansible-artemis#6]
I tried with ubuntu:18.04 and Ubuntu:16.04 image but it's throwing some error while building ansible compatible image.

**Comment by remyma** [comment]
It should work with ubuntu as travis test is executed on it : 
https://github.com/remyma/ansible-artemis/blob/master/.travis.yml

What kind of errors do you have ?

**Comment by onksingh** [comment]
I guess I missed some steps while testing for ubuntu. can you please have a look once?
It's getting failed on     TASK [Create molecule instance(s)] *********************************************

error MSG:
failed: [localhost] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    fatal: [localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}

https://travis-ci.org/onksingh/ansible-artemis

**Comment by remyma** [comment]
ok, sorry, I missawnswered. 
Right now this role was only tested against centos : 
https://github.com/remyma/ansible-artemis/blob/master/molecule/default/molecule.yml

But according to your travis log build your error comes from molecule creating docker images, not from the role itself.
I just added testing against debian like images today. See this pr : https://github.com/remyma/ansible-artemis/pull/7

Should be ok now.

I used the ubuntu image described in this documentation : https://molecule.readthedocs.io/en/latest/examples.html#systemd-container

I close the issue. Feel free to reopen it if neede
